### ISSUE TITLE
can it decrypt data?

### ISSUE THREAD

**Issue by wzsx150** [dg28gadhavi/android_device_nokia_B2N#1]
can it decrypt data?

**Comment by dg28gadhavi** [comment]
Still working on it btw Don't take this tree seriously will make it clean Asap and yeah am trying to fix Encryption/Decryption Hope for the best!!!

**Comment by dg28gadhavi** [comment]
Not yet

**Comment by wzsx150** [comment]
Wish you all the success!

**Comment by dg28gadhavi** [comment]
Fixed
